
"use client"
import '../../styles/globals.css'
import { Inter } from 'next/font/google'

import Header from '../../components/header'
import Sidebar from '../../components/sidebar'

import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { Suspense } from 'react'
import Loading from '../../components/loader'
import { useRouter, usePathname } from 'next/navigation';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function AdminLayout({ children }) {
  const router = useRouter();
  const pathname = usePathname()


  // Check if the current page is login or signup
  console.log(pathname, "dfjkdjf")
  const hideSidebarAndNavbar = pathname === '/admin/login' || pathname === '/admin/signup';
  console.log(hideSidebarAndNavbar, "dfjkdjf")
  return (
    <html lang="en">
      <body className={inter.className}>
        {hideSidebarAndNavbar && (
          <>
            <main>
              <div>
                {children}
              </div>
            </main>
          </>
        )}
        {/* <GlobalState> */}
        {!hideSidebarAndNavbar && (
          <>
            <div className='flex h-screen overflow-hidden'>
              <Sidebar />
              <div className='relative flex flex-1 flex-col overflow-y-auto overflow-x-hidden'>
                <Header />
                <Suspense fallback={<Loading />}>
                  <main>
                    {/* <div className='mx-auto max-w-screen-2xl p-4 md:p-6 2xl:p-10'> */}
                    <div>
                      {children}
                    </div>
                  </main>
                </Suspense>
              </div>
            </div>
          </>
        )}
        <ToastContainer />
        {/* </GlobalState> */}
      </body>
    </html>
  )
}
