
"use client"
import '../../styles/globals.css'
import { Inter } from 'next/font/google'
import { useRouter, usePathname } from 'next/navigation';

import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { Suspense } from 'react'
import Loading from '../../components/loader'
import ClientSidebar from '../../components/clientSidebar';
import ClientHeader from '../../components/clientHeader'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function CLientLayout({ children }) {
  const router = useRouter();
  const pathname = usePathname()

  // Check if the current page is login or signup
  console.log(pathname, "dfjkdjf")
  const hideSidebarAndNavbar = pathname === '/client/login' || pathname === '/client/signup';
  console.log(hideSidebarAndNavbar, "dfjkdjf")
  return (
    <html lang="en">
      <body className={inter.className}>
        {hideSidebarAndNavbar && (
          <>
            <main>
              <div>
                {children}
              </div>
            </main>
          </>
        )}


        {!hideSidebarAndNavbar && (
          <>
            <div className='flex h-screen overflow-hidden'>
              <ClientSidebar />
              <div className='relative flex flex-1 flex-col overflow-y-auto overflow-x-hidden'>
                <ClientHeader />
                <Suspense fallback={<Loading />}>
                  <main>
                    <div>
                      {children}
                    </div>
                  </main>
                </Suspense>
              </div>
            </div>
          </>
        )}


        <ToastContainer />
        {/* </GlobalState> */}
      </body>
    </html>
  )
}
